### ISSUE TITLE
periodo troppo lungo , pesante da leggere

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#14]
https://github.com/WarMachineSwe/WarMachine/blob/06373722995017102ecb10d267fde6cfcdd3321e/rr/interni/norme-di-progetto/sezioni/introduzione_norme.tex#L36

## Expected Behavior
Suggerimento : 
Questo progetto intende creare un software capace di : 
1. creare diagrammi di robustezza
2. creare codice Java e SQL usando come input il diagramma precedentemente creato

## Actual Behavior
mi pare troppo pesante da un punto di vista concettuale. Sarebbe meglio più periodi brevi che vanno dritti al nocciolo della questione.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ShiroAimai** [comment]
Concordo per la suddivisione in elenchi puntati
