### ISSUE TITLE
errore concettuale

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#15]
https://github.com/WarMachineSwe/WarMachine/blob/1de7ecf820a516eaaec4d85966afe4568a0ca5f3/rr/interni/norme-di-progetto/sezioni/Processi_Di_Supporto.tex#L19

Secondo me è concettualmente errato indicare che il documento viene stilato. E' ovvio che il documento segue le regole dopo citate solo se viene creato.

## Expected Behavior
Ogni documento non formale ....

## Actual Behavior
Ogni documento non formale stilato ....

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by acoletti-33100** [comment]
ah a riga 24 c'è un \ senza niente è un errore?

**Comment by acoletti-33100** [comment]
a riga 25 :  In caso il \responsabilediprogetto ritenga che il documento	non sia ancora in grado di essere approvato,....
Cambierei in In caso il \responsabilediprogetto ritenga che il documento non sia approvabile .....

**Comment by ShiroAimai** [comment]
Io lascerei "non sia ancora in grado" visto che son modifiche progressive, almeno da l'idea che prima o poi ci arriverà per gradi appunto
