### ISSUE TITLE
da correggere Studio di Fattibilità

### ISSUE THREAD

**Issue by elezanon** [WarMachineSwe/WarMachine#17]
## Expected Behavior
In Introduzione:
       1.4 Riferimenti normativi: c'è un elenco numerato al posto di un elenco puntato   
       1.5 Riferimenti informativi: mancano i ; alla fine delle righe e mancano alcuni capitolati 

In 2 Capitolato scelto C5:
       2.4 Motivazione della scelta - in 2.4.1 Aspetti positivi: nel secondo punto dell'elenco puntato si ripete due volte "in informatica"
       2.5 Conclusioni: ci sono gli spazi messi "a caso"

In 3 Capitolato C1:
       3.2 Descrizione: nella prima frase compare: " 5glmachine learning", il 5 probabilmente doveva essere un "\".
       3.4 Motivazione della scelta - 3.4.1 Aspetti positivi: nel secondo punto dell'elenco puntato compare: " laurea triennale di informatica dell'università di Padova" che dovrebbe essere invece: " Laurea Triennale in Informatica dell'Università di Padova"

In 4 Capitolato C2:
       4.1 Informazioni sul capitolato: 
                    nel primo punto dell'elenco puntato manca lo spazio qui " BlockCV : blockchain",
                    nel terzo punto manca una virgola tra i nomi dei professori
       4.3 Studio del domino - in 4.3.1 Dominio applicativo: manca un articolo qui: "L'applicazione richiede la costruzione e L'amministrazione "
       4.3.2 Dominio tecnologico: "Per la realizzazione sono necessarie buone conoscenze RIGUARDANTI:"
       4.4 Motivazione della scelta - in 4.4.1 Aspetti positivi:
              • Possibilità di apprendimento DELLA tecnologia blockchain

In 7 Capitolato C6:
       7.5 Conclusione: nella prima frase cambierei:  "il gruppo è arrivato alla conclusione che sebbene
sia una una buona opportunità PER sperimentare nuove tecnologie"
       
8 Capitolato C7:
          8.1 Informazioni sul capitolato: 
                 nel primo punto "Nomelas: " c'è un las di troppo
                 nel terzo manca una , tra i nomi
          8.2 Descrizione: 
                    "L'obiettivo di questo capitolato è QUELLO di realizzare" oppure "L'obiettivo di questo capitolato è realizzare" (senza di)
                     " Lo struemento" -> struMento
          8.3 Studio del domino - in 8.3.1 Dominio applicativo: 
                       Server Kibana: Per l'elaborazione di dati e LA visualizzazione 
          8.3.2 Dominio tecnologico: "Per la realizzazione è necessaria conoscenza riguardanti" è necessaria conoscenza???
          8.4.2 Fattori a rischio: 
                 • Necessita uno studio per quanto riguarda IL lato server

In 9 Capitolato C8:
         9.1 Informazioni sul capitolato: manca una virgola tra i nomi dei professori
         9.4 Motivazione della scelta - in 9.4.1 Aspetti positivi:
                   nel secondo punto manca un verbo o va cambiato il tempo verbale (es.  La possibilità di apprendere React è utile per ....)
                   nel quarto punto:  "Fornito già l'aspetto che dovrà avere idealmente la piattaforma." sarebbe meglio scrivere  "Fornito già l'aspetto che idealmente dovrà avere la piattaforma."
         9.4.2 Fattori a rischio:  "sarebbe necessariA UN'analisi"

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by riccardobek** [comment]
Provate a dare un'ultima occhiata allo studio di fattibilità. Ho apportato tutte le modifiche segnalate.
