### ISSUE TITLE
dimenticanza elenchi ordinati numerici

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#19]
https://github.com/WarMachineSwe/WarMachine/blob/1de7ecf820a516eaaec4d85966afe4568a0ca5f3/rr/interni/norme-di-progetto/sezioni/Processi_Di_Supporto.tex#L77
Manca il caso degli elenchi numerici in cui l' ordine ha rilevanza.
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ShiroAimai** [comment]
Quanti livelli di annidamento hai negli elenchi puntati numerici?

**Comment by acoletti-33100** [comment]
solo 2 però al secondo livello ho usato il trattino come da norma. Direi di dire semplicemente che nel caso
l' ordine conti ad un certo lvl quello è un eccezione quindi usa numeri e non i valori prestabiliti lasciando invariati gli altri livelli a meno che non richiedano numerazione ordinata

**Comment by ShiroAimai** [comment]
Ok ho scritto che il primo livello di un elenco puntato può essere rappresentato tramite un pallino o, in caso di esigenza di ordine, tramite numeri

**Comment by acoletti-33100** [comment]
e che succede se nel primo lvl non serve la numerazione ma serve in uno successivo?

**Comment by ShiroAimai** [comment]
Mmh hai ragione, correggo
