### ISSUE TITLE
errore in piano di qualifica

### ISSUE THREAD

**Issue by sirfoga** [WarMachineSwe/WarMachine#2]
@Bragaz ti sei dimenticato la pasta

- qua
https://github.com/WarMachineSwe/WarMachine/blob/e7e4be4af16e491edb934013d1e42bc65d8c80c6/esterni/rr/piano-di-qualifica/introduzione.tex#L12

- qua
https://github.com/WarMachineSwe/WarMachine/blob/e7e4be4af16e491edb934013d1e42bc65d8c80c6/esterni/rr/piano-di-qualifica/introduzione.tex#L13

- e qua
https://github.com/WarMachineSwe/WarMachine/blob/e7e4be4af16e491edb934013d1e42bc65d8c80c6/esterni/rr/piano-di-qualifica/introduzione.tex#L14

**Comment by sirfoga** [comment]
vedi @ShiroAimai adesso dico a @Bragaz che si è dimenticato la pasta anche qua

https://github.com/WarMachineSwe/WarMachine/blob/e7e4be4af16e491edb934013d1e42bc65d8c80c6/esterni/rr/piano-di-qualifica/introduzione.tex#L14

**Comment by sirfoga** [comment]
@Bragaz hello

**Comment by ShiroAimai** [comment]
gtrht
