### ISSUE TITLE
uso improprio nomi

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#20]
https://github.com/WarMachineSwe/WarMachine/blob/1de7ecf820a516eaaec4d85966afe4568a0ca5f3/rr/interni/norme-di-progetto/sezioni/Processi_Di_Supporto.tex#L82
# Expected Behavior
Penso non vada bene inserire segreatario tra i ruoli di progetto dato che i ruoli ricopribili formalmente
sono solo 6. Lo metteri sotto un' altra sezione (eg : miscellanei , utile se hai robe da aggiungere ma non hai categorie)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ShiroAimai** [comment]
Ho aggiunto questa sottosezione, dimmi se risolve il problema:
\item \textbf{Ruoli per la documentazione}
	\begin{itemize}
		\item \textbackslash segretario = \segretario;
		\item \textbackslash segretari = \segretari;
		\item \textbackslash responsabilediprogetto = \responsabilediprogetto;
		\item \textbackslash verificatore = \verificatore;
		\item \textbackslash verificatori = \verificatori.
	\end{itemize}

**Comment by acoletti-33100** [comment]
si secondo me va bene solo responsabilediprogetto è il responsabile che è uno dei ruoli "formali" dato dal prof quindi va in Ruoli di progetto.

**Comment by ShiroAimai** [comment]
Si, ma è anche quello incaricato di approvare ogni documento quindi sia i verificatori che il responsabile gli ho messi in entrambi

**Comment by acoletti-33100** [comment]
non diventa ridondante? tanto lo hai già indicato , secondo me è  meglio usarlo una sola volta dove è più proprio che sia categorizzato.

**Comment by ShiroAimai** [comment]
Va bene
