### ISSUE TITLE
testo incompleto

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#36]
https://github.com/WarMachineSwe/WarMachine/blob/ff135466c9f95dc93429c804ccd1099e6789d3dc/rr/interni/norme-di-progetto/sezioni/Processi_Primari.tex#L84
## Actual Behavior
I requisiti vengono tracciati tramite ...... per garantire il controllo di conformità. 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ShiroAimai** [comment]
Bisogna ancora fissare il software con cui facciamo il tracciamento dei requisiti

**Comment by acoletti-33100** [comment]
ok
