### ISSUE TITLE
\subsubsubsection size

### ISSUE THREAD

**Issue by Bragaz** [WarMachineSwe/WarMachine#4]
La dimensione di queste ultime è più grande rispetto a quella delle \subsubsection, riesci a risolvere??

**Comment by sirfoga** [comment]
@Bragaz la dimensione solo del titolo o anche del testo?

**Comment by sirfoga** [comment]
![screenshot from 2018-03-21 16-15-40](https://user-images.githubusercontent.com/14162628/37718498-1e516d02-2d23-11e8-8edc-b9a02815dd61.png)

**Comment by sirfoga** [comment]
it seems to me that's ok, maybe a compiling problem of the macos's pdflatex?
