### ISSUE TITLE
incompletezza concettuale

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#43]
https://github.com/WarMachineSwe/WarMachine/blob/69ed0cc66721754102163b33dff323db67360172/rr/interni/norme-di-progetto/sezioni/Processi_Organizzativi.tex#L227
## Expected Behavior
Direi che se scrivi così allora devi inserire nel glossario cosa sono e cosa s'intende per issue tracking ,
pull request e commenti rispetto a github.
Direi di inserire una sottosezione che spiega cos'è Git o metterlo nel glossario indicando che è un 
Distributed Version Control Systems (DVCS) (riferimento: https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control).
Sugggerimento testo alternativo : 
Gli utenti usano GitHub per condividere file. Github offre la possibilità di creare repository pubblici , gratuiti per l' open source e il software libero ,  e anche repository privati , a pagamento e non. ..... 

## Actual Behavior
..... Gli utenti possono interagire tramite un sistema di issue tracking, pull request e commenti che permette di migliorare il codice della repository (privati sia a pagamento, sia gratuiti, molto utilizzati per lo
sviluppo di progetti open-source) risolvendo bug o aggiungendo funzionalità.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ShiroAimai** [comment]
Mettiamo i termini issue tracking e pull sul glossario
