### ISSUE TITLE
Frase introduzione 1.1 PDQ

### ISSUE THREAD

**Issue by izanetti** [WarMachineSwe/WarMachine#54]
## Steps to Reproduce the Problem
"Per ottenere tali obiettivi è necessario un \gl{processo} di verifica continua sulle \gl{attività} svolte in modo da consentire il rilevamento e la correzione di anomalie e incongruenze in modo tempestivo
e con un limitato spreco di risorse." 
Troppe e, frase troppo lunga. Io toglierei l'ultima  "e"

**Comment by sirfoga** [comment]
fixed in 4f322519f3a9aa3f844eb1171623e94fc7ca3355
