### ISSUE TITLE
Incorrettezze introduzione

### ISSUE THREAD

**Issue by ShiroAimai** [WarMachineSwe/WarMachine#59]
## Expected Behavior
Gli standard sono dei riferiementi normativi non informativi

## Actual Behavior
https://github.com/WarMachineSwe/WarMachine/blob/b0c151914deea847988a643cd3ef900ce7dec784/rr/esterni/piano-di-qualifica/sezioni/Introduzione.tex#L25

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by Bragaz** [comment]
sistemato
