### ISSUE TITLE
Errori nella forma

### ISSUE THREAD

**Issue by ShiroAimai** [WarMachineSwe/WarMachine#61]
## Expected Behavior
"in maniera oggettiva"

## Actual Behavior
https://github.com/WarMachineSwe/WarMachine/blob/b0c151914deea847988a643cd3ef900ce7dec784/rr/esterni/piano-di-qualifica/sezioni/Qualita.tex#L40

"In maniera più oggettiva possibile" non è formale

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by Bragaz** [comment]
https://github.com/WarMachineSwe/WarMachine/blob/ffbd1ddc4c338dd1dfc06d422c831e10fda253d5/rr/esterni/piano-di-qualifica/sezioni/Qualita.tex#L40

così può andare?
