### ISSUE TITLE
errore verbale e morfologico

### ISSUE THREAD

**Issue by acoletti-33100** [WarMachineSwe/WarMachine#9]
## Expected Behavior
qualora i \verificatori trovassero degli errori nella documentazione , devono segnalare i problemi al \responsabilediprogetto che a sua volta incarica i \segretari di apportare le dovute modifiche; 

## Actual Behavior
https://github.com/WarMachineSwe/WarMachine/blob/30813a68ae0232bfc4f71f73dd7fa975f2309b41/rr/interni/norme-di-progetto/sezioni/Processi_Di_Supporto.tex#L23

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ShiroAimai** [comment]
Te l'ho corretto, ma come sei fiscale eh

**Comment by acoletti-33100** [comment]
lo so gazie
